//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IDAStealth.rc
//
#define IDD_ABOUT                       102
#define IDR_LOGO                        103
#define IDD_DIALOG1                     106
#define IDD_DIALOG2                     107
#define IDD_DIALOG3                     108
#define IDD_DIALOG4                     109
#define IDD_INPUTBOX                    110
#define IDR_DRV1                        114
#define IDR_DRV2                        124
#define IDD_CHOOSE                      125
#define IDR_RDTSC                       126
#define IDR_DRV3                        127
#define IDR_STEALTH                     127
#define IDC_NTQSI                       1006
#define IDC_DBGPRESENT                  1007
#define IDC_DBGATTACH                   1008
#define IDC_NTGF                        1009
#define IDC_NTHF                        1010
#define IDC_NTSIT                       1011
#define IDC_NTQO                        1012
#define IDC_DBGSTART                    1013
#define IDC_OUTDBGSTR                   1014
#define IDC_NTCLOSE                     1015
#define IDC_NEWGRE                      1016
#define IDC_NTQIP                       1017
#define IDC_PROTECTDRS                  1018
#define IDC_GETTICKCOUNT                1019
#define IDC_PARENTPROCESS               1020
#define IDC_RTLNTGF                     1021
#define IDC_HIDEIDAPROCESS              1022
#define IDC_BLOCKINPUT                  1023
#define IDC_DISSUSPEND                  1024
#define IDC_SUSPENDTHREAD               1024
#define IDC_DBGPRNTEXCEPT               1026
#define IDC_NTYIELD                     1027
#define IDC_ANTIATTACH                  1028
#define IDC_OPENPROCESS                 1029
#define IDC_SWITCH                      1030
#define IDC_RDTSC                       1031
#define IDC_HIDEIDAWND                  1032
#define IDC_NTSIT_DRV                   1032
#define IDC_NTQIP_DRV                   1033
#define IDC_GETVERSION                  1035
#define IDC_TERMINATE                   1036
#define IDC_LOGO                        1037
#define IDC_UNLOAD_DRIVER               1037
#define IDC_UNLOAD_STEALTH_DRV          1038
#define IDC_RDTSC_ZERO                  1039
#define IDC_RDTSC_INCREASING            1040
#define IDC_RDTSC_DELTA                 1041
#define IDC_CHECK1                      1042
#define IDC_RAND_NAME                   1042
#define IDC_PASS_EXCEPTIONS             1042
#define IDC_RDTSC_DELTA2                1043
#define IDC_TICK_DELTA                  1043
#define IDC_SYSLINK1                    1046
#define IDC_SYSLINK                     1046
#define IDC_RADIO1                      1047
#define IDC_AUTO_SELECTION              1047
#define IDC_RADIO2                      1048
#define IDC_FORCE_ABS                   1048
#define IDC_RADIO3                      1049
#define IDC_PUSH_RET                    1049
#define IDC_COMBO1                      1050
#define IDC_PROFILES                    1050
#define IDC_BUTTON1                     1052
#define IDC_ADD_PROFILE                 1052
#define IDC_OPTIONS                     1052
#define IDC_BUTTON2                     1053
#define IDC_DEL_PROFILE                 1053
#define IDC_LOG                         1053
#define IDC_BUTTON3                     1054
#define IDC_RADIO4                      1055
#define IDC_PUSH_MOV_JMP                1055
#define IDC_EDITBOX                     1056
#define IDC_EDIT1                       1057
#define IDC_TCP_PORT                    1057
#define IDC_CHECK3                      1060
#define IDC_HANDLER_HALT                1060
#define IDC_HALT_IN_SEH                 1060
#define IDC_CHECK4                      1061
#define IDC_HALT_AFTER_SEH              1061
#define IDC_CHECK5                      1062
#define IDC_LOG_AFTER_SEH               1062
#define IDC_LOG_SEH                     1062
#define IDC_CHECK6                      1063
#define IDC_CHECK7                      1064
#define IDC_CLOSE                       1064
#define IDC_CHECK8                      1065
#define IDC_CHECK9                      1072
#define IDC_CHECK10                     1073
#define IDC_CHECK11                     1074
#define IDC_CHECK12                     1075
#define IDC_CHECK13                     1076
#define IDC_CHECK14                     1077
#define IDC_CHECK15                     1078
#define IDC_CHECK16                     1079
#define IDC_CHECK17                     1080
#define IDC_CHECK18                     1081
#define IDC_CHECK19                     1082
#define IDC_CHECK20                     1083
#define IDC_CHECK21                     1084
#define IDC_CHECK22                     1085
#define IDC_CHECK23                     1086
#define IDC_CHECK24                     1087
#define IDC_CHECK25                     1094
#define IDC_CHECK26                     1095
#define IDC_CHECK27                     1096
#define IDC_CHECK28                     1097
#define IDC_CHECK29                     1098
#define IDC_CHECK30                     1099
#define IDC_CHECK31                     1100
#define IDC_CHECK32                     1101
#define IDC_CHECK33                     1102
#define IDC_CHECK34                     1103

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
